name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100 # .NET Core 3 LTS
    - name: List available SDKs # Just to be sure it's there!
      run: dotnet --list-sdks
    - name: Build with dotnet   # GOGOGO!
      run: dotnet build ./src/Streetlight.sln --configuration Release
